shared:
    image: node:6
jobs:
    main:  
        steps:
            - install: npm install screwdriver-template-main
            # this is run by the PRs as well
            - validate: ./node_modules/.bin/template-validate
        annotations:
            screwdriver.cd/buildPeriodically: '* * * * *'
        requires: [~pr,~commit]
    sample3:
        steps:
            - echo: echo "baz"
        annotations:
            screwdriver.cd/buildPeriodically: 'M N O P Q'
        requires: [~pr, ~commit]
    sample4:
        steps:
            - echo: echo "baz"
        annotations:
            screwdriver.cd/buildPeriodically: '* * * * *'
        requires: [~pr, ~commit]
    sample6:
        steps:
            - echo: echo "baz"
        annotations:
            screwdriver.cd/buildPeriodically: '* * * * *'
        requires: [~pr, ~commit]
    sample7:
        steps:
            - echo: echo "baz"
        annotations:
            screwdriver.cd/buildPeriodically: '5 4 5 Jan Sun'
        requires: [~pr, ~commit]
    sample8:
        steps:
            - echo: echo "baz"
        annotations:
            screwdriver.cd/buildPeriodically: '15 20 7 May *'
        requires: [~pr, ~commit]
    publish:
        steps:
            - install: npm install screwdriver-template-main
            # publishing also validates
            - publish: ./node_modules/.bin/template-publish
        requires: [main]
