shared:
    image: node:6
jobs:
    main:  
        steps:
            - install: npm install screwdriver-template-main
            # this is run by the PRs as well
            - validate: ./node_modules/.bin/template-validate
        annotations:
            screwdriver.cd/buildPeriodically: '* * * * *'
        requires: [~pr,~commit]
    sample1:
        steps:
            - echo: echo "foo"
        annotations:
            screwdriver.cd/buildPeriodically: '* * * * *'
        requires: [~pr, ~commit]
    sample2:
        steps:
            - echo: echo "bar"
        annotations:
            screwdriver.cd/buildPeriodically: '* * * * *'
        requires: [~pr, ~commit]
    sample3:
        steps:
            - echo: echo "baz"
        annotations:
            screwdriver.cd/buildPeriodically: '* * * * *'
        requires: [~pr, ~commit]
    publish:
        steps:
            - install: npm install screwdriver-template-main
            # publishing also validates
            - publish: ./node_modules/.bin/template-publish
        requires: [main]
